eight_points_guzzle:
    clients:
        agency_api:
            # Write here the host where to do requests
            # base_url: "http://target.url"

            options:
                timeout: 30
                auth:
                    - api     # login
                    - api     # password

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: "EightpointsGuzzleBundle/7.0"
                    Accept: "application/json"

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~
